title: My New Beaker Site
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude:
  - node_modules
  - gulpfile.js
  - gulpconfig.json
  - package.json
  - config.rb
  - npm-debug.log
  - README.md
