# Site settings
title: My New Frasco Site
description: Jekyll starter project including full setup for Gulp, Sass, Autoprefixer, Bourbon/Neat/Bitters, Browserify, Imagemin, Browsersync, etc.
url: http://ixkaito.github.io # the base hostname & protocol for your site
baseurl: '/frasco' # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
exclude:
  - node_modules
  - gulpfile.js
  - gulpconfig.json
  - package.json
  - npm-debug.log
  - README.md
  - LICENSE
