# Site settings
title: 'Frasco: Jekyll Starter Project'
description: Quick starter project for Jekyll including full setup for gulp, Sass, Autoprefixer, Bourbon/Neat/Bitters, Webpack, Imagemin, Browsersync, etc.
url: https://ixkaito.github.io # the base hostname & protocol for your site
baseurl: '/frasco' # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
exclude:
  - frasco.config.js
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - README.md

compress_html:
  # clippings: all
  comments: all
  # endings: all
  ignore:
    envs: [development]
  # blanklines: true
  # profile: true
  # startings: [html, head, body]

twitter:
  id: ixkaito

facebook:
  admin: 1047363919
